openapi: 3.0.1
info:
    title: wx-yolo
    description: 这是一个视频分析插件，用户会向你发送 bilibili 视频链接，你需要调用接口获得视频目标检测结果再对视频进行分析。
    version: "v1"
servers:
    - url: PLUGIN_HOST
paths:
    /detect:
        post:
            operationId: detect
            summary: 对视频进行目标检测
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/detect_request"
            responses:
                "200":
                    description: 目标检测结果
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/detect_response"
components:
    schemas:
        detect_request:
            type: object
            required: [url]
            properties:
                url:
                    type: string
                    description: 用户需要分析的视频网址
        detect_response:
            type: object
            description: 目标检测结果
            properties:
                err:
                    type: string
                    description: 如果检测失败，这个字段表示失败的原因
                prompt:
                    type: string
                    description: 提示词
                frames:
                    type: array
                    description: 帧的目标检测结果列表
                    items:
                        type: object
                        description: 目标检测结果
                        properties:
                            time:
                                type: number
                                description: 帧所在视频的时间
                            objs:
                                type: array
                                description: 该帧检测到的目标列表
                                items:
                                    type: object
                                    description: 检测到的目标
                                    properties:
                                        obj:
                                            type: string
                                            description: 目标类型
                                        xywh:
                                            type: array
                                            description: 长度为 4 的整数数组，4 个元素分别代表目标的 X 坐标，Y 坐标，宽度，长度
                                            items:
                                                type: number